20200808_module_user_register_avances
trazzos/comprobante_backend pull request #7
Opened 2020-08-08 20:55 UTC by aristasoluciones

Registro  y verificacion de correo

2020-08-17 14:10 UTC, mwleinad commented on Modules/User/Services/AuthRegisterService.php
> +            event(new Registered($user));
Hay posibilidad de que esto falle?
Segun yo no.
El evento se manda
crea una instancia de Registered. 
Eso manda a llamar a un listener no?
https://laravel.com/docs/7.x/events#handling-failed-jobs
El listener tiene un metodo failed que es el que hace el desmadre si algo falla. Dependiendo de tus settings

2020-08-17 14:10 UTC, mwleinad commented on Modules/User/Services/AuthVerifyService.php
> +
😮

2020-08-17 14:11 UTC, mwleinad commented on app/Http/Controllers/Auth/VerificationController.php
> +    //protected $redirectTo = '/home';
quitar?

2021-01-19 20:19 UTC, aristasoluciones commented on Modules/Branch/Models/Branch.php
> +    protected $fillable = ['name', 'company_id', 'zip_code', 'user_id'];
Debido a que esto de fillable lo realizaba por que mandaba datos desde registrarse y ese lo usaba en varios modelos , tonces se me hizo facil eso, ahora lo que realice fue normalizar desde el Modules\User\Services\AuthRegisterService.php, lo mismo aplica para  El model company

2021-01-19 20:20 UTC, aristasoluciones commented on Modules/Company/Models/Company.php
> +    protected $fillable = ['name', 'taxpayer_id'];
lo mismo que Company

2021-01-20 15:54 UTC, aristasoluciones commented on Modules/User/Http/Controllers/Auth/VerificationController.php
> +            return $this->handleAjaxJsonResponse($response, 'El correo ya se encuentra verificado.');
utilice un metodo privado para ambos , a ver si cumple el estandar

2021-01-20 20:51 UTC, aristasoluciones commented on Modules/User/Services/AuthRegisterService.php
> +            event(new Registered($user));
es correcto

2021-01-20 20:51 UTC, aristasoluciones commented on Modules/User/Services/AuthVerifyService.php
> +
remove

2021-01-20 22:04 UTC, mwleinad requested changes

2021-01-20 22:04 UTC, mwleinad commented on Modules/Branch/Models/Branch.php
> +    protected $fillable = [];
creeeeo que este lo tienes que quitar, no estoy 100% seguro
pero aqui basicamente estas diciendo que no permitas ningun campo fillable

2021-01-20 22:04 UTC, mwleinad commented on Modules/Company/Models/Company.php
> +    protected $fillable = [];
igual

2021-01-20 22:04 UTC, mwleinad commented on Modules/User/Http/Controllers/VerificationController.php
> +    private function handleVerify(User $user, $resend = false) : JsonResponse {
cambiarlo a como platicamos, y crear el nuevo servicio.

2021-01-20 22:04 UTC, mwleinad commented on Modules/User/Models/User.php
> +    protected $fillable = [];
quitar

2021-01-20 22:04 UTC, mwleinad commented on database/migrations/2021_01_19_045037_alter_multiple_table.php
> +class AlterMultipleTable extends Migration
jajaja podrias ser mas especifico con el nombre? alter_user_and_branch

2021-01-21 04:56 UTC, aristasoluciones commented on database/migrations/2021_01_19_045037_alter_multiple_table.php
> +class AlterMultipleTable extends Migration
Sale asi lo hare haha

2021-01-21 05:35 UTC, aristasoluciones commented on Modules/Branch/Models/Branch.php
> +    protected $fillable = [];
Lo quite pero funciona con los dos, bueno  hice mis pruebas antes cuando lo tenia y si insertaba.
Entonces creo no importa, pero de todos modos ya la quite.

2021-01-21 05:37 UTC, aristasoluciones commented on Modules/User/Http/Controllers/VerificationController.php
> +    private function handleVerify(User $user, $resend = false) : JsonResponse {
Deje esos metodos como controller de una sola accion .

2021-01-21 16:06 UTC, mwleinad requested changes

2021-01-21 16:06 UTC, mwleinad commented on Modules/User/Http/Controllers/ResendVerificationController.php
> +        $response = $this->authVerifyService->resend($request);
Me gusto como lo separaste, solo aqui creo que podrias directamente usar $user no? en vez de devolver ese valor de la funcion
$user = $this->info($request->route('id'));

No estas haciendo ninguna modificacion del valor de user, simplemente lo estas enviando y regresando tal cual jaja

2021-01-21 16:06 UTC, mwleinad commented on Modules/User/Http/Controllers/ResendVerificationController.php
> +        $response = $this->authVerifyService->resend($request);
del controlador a los servicios no es buena practica enviar el objecto de request. Aqui enviaria solo lo que necesita. Ver otros comentarios

2021-01-21 16:06 UTC, mwleinad commented on Modules/User/Services/AuthVerifyService.php
> +        $user = $this->info($request->route('id'));
como te comente, este mejor que no vaya

2021-01-21 16:06 UTC, mwleinad commented on Modules/User/Services/AuthVerifyService.php
> +        return [$user, $message];
aqui mejor regresar solo un string $message

2021-01-21 16:06 UTC, mwleinad commented on Modules/User/Services/AuthVerifyService.php
> +    public function verify(Request $request) {
ni siquiera es necesario que pases el $request no?

2021-01-21 16:06 UTC, mwleinad commented on Modules/User/Services/AuthVerifyService.php
> +    public function resend(Request $request) {
Aqui en vez de enviar Request $request mejor enviar User $user

2021-01-21 16:06 UTC, mwleinad commented on Modules/User/Services/AuthVerifyService.php
> +        return [$user, $message];
retornar solo string $message

2021-01-23 19:01 UTC, merged